spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.31.120:3306/jboot?characterEncoding=utf8&serverTimezone=Hongkong&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: root

  jpa:  # 仅仅使用Hibernate自动更新表结构，底层数据库操作依然使用MyBatis
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    database: 2
    host: 192.168.31.120
    port: 6379
    password:
    timeout: 6000  # 连接超时时长（毫秒）

logging:
  config: classpath:log4j2/log4j2.xml

