server:
  port: 8902

spring:
  application:
    name: study-sentinel
  cloud:
    sentinel:
      log:
        dir: ${user.home}/logs/sentinel # sentinel日志存储目录，连接成功与否可查看日志“sentinel-record.log”
      transport:
        dashboard: localhost:8858 # sentinel控制台地址
