server:
  port: 8900

spring:
  application:
    name: netty

fank243:
  netty:
    server:
      ws:
        enable: true
        ip: 0.0.0.0
        port: 9000
      tcp:
        enable: true
        ip: 0.0.0.0
        port: 9001
