server:
  port: 8900
  max-http-header-size: 65546 # 设置HTTP响应头大小

spring:
  application:
    name: fank243-admin
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 解决@ControllerAdvice无法捕捉404异常
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

jetcache:
  statIntervalMinutes: 15 # 统计间隔时间，单位：分钟
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50