server:
  port: 8901

spring:
  application:
    name: fank243-app
  profiles:
    active: dev

jetcache:
  statIntervalMinutes: 15 # 统计间隔时间，单位：分钟
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50