# 原生 MyBatis 所支持的配置，具体请查看 https://baomidou.com/config/#configuration-2
mybatis-plus:
  configuration:
    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 列字段采用驼峰命名
    map-underscore-to-camel-case: true

  # MyBatis-Plus 全局策略配置，具体请查看 https://baomidou.com/config/#globalconfig-2
  global-config:
    # MyBatis-Plus 全局策略中的 DB 策略配置，具体请查看 https://baomidou.com/config/#dbconfig-2
    db-config:
      # 主键ID生成策略，雪花算法
      id-type: ASSIGN_ID
      # 表名前缀
      table-prefix: tb_
      # 全局的entity的逻辑删除字段属性名
      logic-delete-field: is_deleted
      # 逻辑已删除值
      logic-not-delete-value: 0
      # 逻辑未删除值
      logic-delete-value: 1
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略
      insert-strategy: NOT_EMPTY
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      update-strategy: NOT_EMPTY
